3 rest
Tavkel/Shelter pull request #19
Opened 2023-10-17 13:44 UTC by warlocktony

my caracules

2023-10-18 19:35 UTC, Tavkel requested changes

2023-10-18 19:35 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/models/domain/Pet.java
>                  && Objects.equals(pathToFile, pet.pathToFile)
remove сравнение по фотке

2023-10-18 19:35 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/models/domain/Pet.java
> +                fileSize, mediaType, pathToFile, description, specialNeeds);
убрать поля фотки из хэша

2023-10-18 19:35 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/services/implementations/PetServiceImpl.java
> +    }
выпиливаем

2023-10-18 19:35 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/services/interfaces/PetService.java
> +    Pet getPetPhotoPreview(long id);
выпиливаем

2023-10-20 08:10 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/models/domain/Pet.java
>                  && Objects.equals(pathToFile, pet.pathToFile)
+

2023-10-20 08:11 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/models/domain/Pet.java
>                  && Objects.equals(pathToFile, pet.pathToFile)
remove fileSize, mediaType and photo in method equals

2023-10-20 08:12 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/models/domain/Pet.java
> +                fileSize, mediaType, pathToFile, description, specialNeeds);
remove fileSize, mediaType and photo in method hashCode

2023-10-20 08:14 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/services/implementations/PetServiceImpl.java
> +    }
slish ment , method getPetPhotoPreview mne vipili blyat

2023-10-20 08:15 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/services/implementations/PetServiceImpl.java
> +    }
ispolneno

2023-10-20 08:16 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/services/interfaces/PetService.java
> +    Pet getPetPhotoPreview(long id);
done

2023-10-20 20:49 UTC, merged