3 rest
Tavkel/Shelter pull request #8
Opened 2023-10-11 18:12 UTC by warlocktony

first sprint

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/PetController.java
> +        return petService.reade(id);
read

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/PetController.java
> +public class PetController {
Добавить возможность "посмотреть всех". с пагинацией, по 5 штук на страницу

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/PetController.java
> +public class PetController {
Добавить загрузку фотки отдельно

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/ReportController.java
> +    @GetMapping("/{id}")
Добавить GET на все репорты от овнера

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/OwnerController.java
> +@RequestMapping("/pet")
путь

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/ControllerExceptionHendler.java
> +public class ControllerExceptionHendler {
Handler

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/ControllerExceptionHendler.java
> +    public ResponseEntity<String> handlerException(Exception ex) {
handler -> handle

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/DTO/ReportDTO.java
> +    public ReportDTO(Long reportIdDTO, Long ownerIdDTO, Long petIdDTO,
Добавить пусты конструкторы,
equals & hashcode

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/DTO/PetDTO.java
> +    private OwnerDTO ownerDTO;
Убираем поля с другими объектами

2023-10-11 19:24 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/DTO/AdoptionRequestDTO.java
> +    private Long ownerIdDTO;
убрать "DTO" из имени

2023-10-12 20:46 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/controllers/ReportController.java
> +    @GetMapping("/{id}")
добавлено

2023-10-12 20:46 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/controllers/PetController.java
> +        return petService.reade(id);
исправлено

2023-10-12 20:46 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/controllers/OwnerController.java
> +@RequestMapping("/pet")
исправлено

2023-10-12 20:46 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/controllers/ControllerExceptionHendler.java
> +    public ResponseEntity<String> handlerException(Exception ex) {
исправлено

2023-10-12 20:46 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/controllers/ControllerExceptionHendler.java
> +public class ControllerExceptionHendler {
исправлено

2023-10-12 20:46 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/DTO/ReportDTO.java
> +    public ReportDTO(Long reportIdDTO, Long ownerIdDTO, Long petIdDTO,
добавлено во все ДТО

2023-10-12 20:46 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/DTO/PetDTO.java
> +    private OwnerDTO ownerDTO;
исправлено

2023-10-12 20:46 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/DTO/AdoptionRequestDTO.java
> +    private Long ownerIdDTO;
исправлено

2023-10-14 19:06 UTC, Tavkel requested changes

2023-10-14 19:06 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/AdoptionRequestController.java
> +    private final int maxFileSizeInKb = 300;
Перенести в application.properties

2023-10-14 19:06 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/ControllerExceptionHendle.java
> +public class ControllerExceptionHandle {
Handler

2023-10-14 19:06 UTC, Tavkel commented on src/main/java/zhy/votniye/Shelter/controllers/ReportController.java
> +    public Collection<Owner> readAllReportsByOwner(){
RequestParam long ownerId
Отдает Collection<ReportDTO>

2023-10-14 19:55 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/controllers/ReportController.java
> +    public Collection<Owner> readAllReportsByOwner(){
дело сделано

2023-10-14 20:00 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/controllers/ControllerExceptionHendle.java
> +public class ControllerExceptionHandle {
дело сделано

2023-10-14 20:00 UTC, warlocktony commented on src/main/java/zhy/votniye/Shelter/controllers/AdoptionRequestController.java
> +    private final int maxFileSizeInKb = 300;
готово

2023-10-15 08:13 UTC, Tavkel approved these changes
accepted

2023-10-15 08:13 UTC, merged